#!/bin/bash

echo "* Starting node-pool ..."

/usr/bin/geth --identity "Pool" --rpc --rpcaddr "0.0.0.0" --rpcport "11001" --rpccorsdomain "*" \
--datadir "/data/node-pool" --port "30303" --nodiscover --rpcapi "db,eth,net,web3,admin,personal" \
--nodekeyhex "e0e1f052ea0cd9df43d1c0a7035e871d152cadedb85b740d7e97f867e55ff462"
--unlock "0xfbecb64c03c1f2cf36f39b6bfe4024f019292cbe" --password /data/pw.txt \
--networkid 1900 --verbosity 5

s6-svc -d /var/run/s6/services/node-pool
